#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck source=/dev/null
#
# Copyright (C) 2020-21 UtsavBalar1231 <utsavbalar1231@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd /drone/src/
HOME="/drone/src/"

# Export Build username
export KBUILD_BUILD_USER="UtsavTheCunt"
export KBUILD_BUILD_HOST="CuntsSpace"

# Enviromental Variables

# Set the last commit author
AUTHOR=`git log $BRANCH -1 --format="%an"`

# Set the current branch name
BRANCH=`git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'`

# Set the last commit sha
COMMIT=`git log $BRANCH -1 --format="%h / %s"`

# Set current date
DATE=$(date +"%d.%m.%y")

ls -l

bash build_alioth.sh
