#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck source=/dev/null
#
# Copyright (C) 2020-21 UtsavBalar1231 <utsavbalar1231@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd /drone/src/ || exit

# Anykernel3
if [[ "$@" =~ "alioth"* ]]; then
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b alioth anykernel
elif [[ "$@" =~ "apollo"* ]]; then
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b apollo anykernel
elif [[ "$@" =~ "cmi"* ]]; then
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b cmi anykernel
elif [[ "$@" =~ "umi"* ]]; then
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b umi anykernel
elif [[ "$@" =~ "raphael"* ]]; then
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b master anykernel
else
        git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b alioth anykernel
fi

# Clone compiler
if [[ "$@" =~ "benzoclang"* ]]; then
        git clone https://github.com/lineageos/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 --depth=1 -b lineage-18.1 arm64-gcc
        git clone https://github.com/lineageos/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 --depth=1 -b lineage-18.1 arm32-gcc
        git clone https://github.com/BenzoRom/benzoclang-13.0 --depth=1 clang
elif [[ "$@" =~ "proton"* ]]; then
        git clone https://github.com/kdrag0n/proton-clang -b master --depth=1 clang
else
        git clone https://github.com/kdrag0n/proton-clang -b master --depth=1 clang
fi
