#!/usr/bin/env bash
# shellcheck disable=SC2199
# shellcheck source=/dev/null
#
# Copyright (C) 2020-21 UtsavBalar1231 <utsavbalar1231@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

cd /drone/src/ || exit

# Anykernel3
git clone https://github.com/UtsavBalar1231/Anykernel3 --depth=1 -b exynos anykernel

## Remove .git
rm -fr anykernel/.git

# Clone compiler
if [[ "$@" =~ "gcc"* ]]; then
	git clone --depth=1 https://github.com/mvaisakh/gcc-arm64 --depth=1 gcc64
	git clone --depth=1 https://github.com/mvaisakh/gcc-arm --depth=1 gcc32
else
	git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 -b lineage-18.1 --depth=1 gcc32
	git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 -b lineage-18.1 --depth=1 gcc64
	git clone https://github.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r416183b1 -b 11.0 --depth=1 clang
fi
